# Generated by Django 5.0.7 on 2024-08-31 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_cd', models.CharField(max_length=10)),
                ('sap_cd', models.CharField(max_length=10)),
                ('batch_wt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uom', models.CharField(max_length=10)),
                ('spg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RawGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_cd', models.CharField(max_length=10)),
                ('grp_des', models.CharField(max_length=240)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recepi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_cd', models.CharField(max_length=10)),
                ('rm_cd', models.CharField(max_length=10)),
                ('uom', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RawMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_cd', models.CharField(max_length=10)),
                ('sap_cd', models.CharField(max_length=10)),
                ('rm_des', models.CharField(max_length=240)),
                ('uom', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grp_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='product.rawgrp')),
            ],
        ),
    ]
