# Generated by Django 5.0.7 on 2024-09-01 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepi',
            name='comp_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.compound'),
        ),
        migrations.AlterField(
            model_name='recepi',
            name='rm_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawmat'),
        ),
    ]
