# Generated by Django 5.0.7 on 2024-09-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_recepi_comp_cd_alter_recepi_rm_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepi',
            name='uom',
        ),
    ]
