# Generated by Django 5.0.7 on 2024-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_recepi_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmat',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
