# Generated by Django 5.0.7 on 2024-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rawmat_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='comp_des',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepi',
            name='card_no',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepi',
            name='doc_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepi',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
