# Generated by Django 5.0.7 on 2024-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_compound_comp_des_recepi_card_no_recepi_doc_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='batch_wt',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='compound',
            name='spg',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recepi',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
