# Generated by Django 5.0.7 on 2024-10-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_compound_batch_wt_alter_compound_spg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepi',
            name='unit',
        ),
        migrations.AddField(
            model_name='recepi',
            name='ver',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
