# Generated by Django 5.0.7 on 2024-10-03 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_recepi_unit_recepi_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepi',
            name='ver',
            field=models.CharField(default='V-1', max_length=5),
        ),
        migrations.CreateModel(
            name='MixProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_no', models.CharField(max_length=10)),
                ('prod_dt', models.DateField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=7)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixprod_card_no', to='product.recepi')),
                ('ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixprod_ver', to='product.recepi')),
            ],
        ),
    ]
