# Generated by Django 5.0.7 on 2024-10-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_recepi_ver_mixprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixprod',
            name='ver',
        ),
        migrations.RemoveField(
            model_name='recepi',
            name='ver',
        ),
    ]
