# Generated by Django 4.1 on 2024-07-30 15:35

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.CharField(max_length=20)),
                ("ename", models.CharField(max_length=100)),
                ("eemail", models.EmailField(max_length=254)),
                ("econtact", models.CharField(max_length=250)),
                (
                    "prof_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=employee.models.get_image_path,
                        verbose_name="Attachment(image)",
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
