# Generated by Django 5.0.7 on 2024-08-11 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_url_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.CharField(default='08-12-2024', max_length=255),
            preserve_default=False,
        ),
    ]
